import { useEffect, useState } from 'react';
import { ArrowRight, Mail, Search, Sparkles, Terminal } from 'lucide-react';
import { api } from '../services/api';
import PostCard from '../components/PostCard';
import Loading from '../components/Loading';

const projects = [
  { title: 'Student Management System', description: 'Role-based academic platform with REST APIs and a server-rendered interface.', tech: ['Spring Boot', 'Hibernate', 'MySQL'] },
  { title: 'Hand Gesture Recognition', description: 'Real-time computer vision translating gestures into accessible commands.', tech: ['Python', 'TensorFlow', 'OpenCV'] },
  { title: 'Instagram Database Design', description: 'Normalized social platform data model with optimized query patterns.', tech: ['MySQL', 'SQL', 'ER Design'] },
];

export default function Home() {
  const [posts, setPosts] = useState(null);
  const [search, setSearch] = useState('');
  useEffect(() => { api.get(`/posts?limit=3${search ? `&search=${encodeURIComponent(search)}` : ''}`).then((data) => setPosts(data.items)).catch(() => setPosts([])); }, [search]);
  return <main>
    <section className="relative overflow-hidden border-b border-[#263b2d] bg-[#101a14] text-white"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-24 md:grid-cols-[1.2fr_.8fr] md:items-center md:py-32"><div><div className="mb-6 flex items-center gap-2 text-sm font-medium text-blue-400"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400" /> Available for opportunities</div><h1 className="serif max-w-2xl text-6xl leading-[.98] tracking-tight md:text-8xl">Building systems that <em className="text-blue-400">matter.</em></h1><p className="mt-7 max-w-xl text-lg leading-8 text-gray-400">I’m <strong className="text-white">Akash Bondada</strong>, an MCA graduate and Java Full Stack Developer focused on reliable backend systems and thoughtful APIs.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#blogs" className="rounded-xl bg-blue-500 px-5 py-3 text-sm font-semibold">Read my writing <ArrowRight className="ml-2 inline" size={16} /></a><a href="#projects" className="rounded-xl border border-[#4b6655] px-5 py-3 text-sm font-semibold">View projects</a></div></div><div className="hidden rounded-2xl border border-[#385243] bg-[#17251c] p-6 font-mono text-sm leading-8 text-gray-300 shadow-2xl md:block"><div className="mb-5 text-gray-500">// akash.java</div><span className="text-violet-400">public class</span> <span className="text-blue-300">Akash</span> {'{'}<br />&nbsp;&nbsp;<span className="text-violet-400">String</span> role = <span className="text-emerald-300">"developer"</span>;<br />&nbsp;&nbsp;<span className="text-violet-400">String[]</span> focus = {'{'} <span className="text-amber-300">"Spring Boot", "APIs", "SQL"</span> {'}'};<br />{'}'}</div></div></section>
    <section className="border-b border-[#dce5dc] bg-white dark:bg-[#19271e]"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-12 md:grid-cols-4"><div><b className="text-3xl text-blue-500">07</b><p className="text-sm text-gray-500">Months training</p></div><div><b className="text-3xl text-blue-500">03</b><p className="text-sm text-gray-500">Production-style projects</p></div><div><b className="text-3xl text-blue-500">REST</b><p className="text-sm text-gray-500">API experience</p></div><div><b className="text-3xl text-blue-500">Java + Python</b><p className="text-sm text-gray-500">Daily toolkit</p></div></div></section>
    <section id="projects" className="bg-[#eef4ef] py-24 dark:bg-[#182a1d]"><div className="mx-auto max-w-6xl px-5"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-500">Selected work</p><h2 className="serif mb-10 mt-3 text-5xl dark:text-white">Things I’ve built.</h2><div className="grid gap-6 md:grid-cols-3">{projects.map((project, index) => <article key={project.title} className="rounded-2xl border border-[#d6e3d8] bg-white p-6 transition hover:-translate-y-2 hover:shadow-xl dark:border-[#304638] dark:bg-[#1d2d23]"><div className="mb-12 flex justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#17251c] text-blue-400"><Terminal size={20} /></span><span className="font-mono text-sm text-gray-500">0{index + 1}</span></div><h3 className="serif text-2xl dark:text-white">{project.title}</h3><p className="mt-3 min-h-16 text-sm leading-6 text-gray-500 dark:text-gray-300">{project.description}</p><div className="mt-5 flex flex-wrap gap-2">{project.tech.map((tech) => <span key={tech} className="rounded-md bg-sage px-2 py-1 text-xs text-moss">{tech}</span>)}</div></article>)}</div></div></section>
    <section id="blogs" className="border-t border-[#dce5dc] bg-white py-24 dark:bg-[#19271e]"><div className="mx-auto max-w-6xl px-5"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-500">From the journal</p><h2 className="serif mt-3 text-5xl dark:text-white">Notes from the stack.</h2></div><div className="relative"><Search className="absolute left-3 top-3 text-gray-400" size={17} /><input placeholder="Search posts" value={search} onChange={(event) => setSearch(event.target.value)} className="rounded-xl border border-[#dce5dc] bg-cream py-2.5 pl-10 pr-4 text-sm outline-none dark:border-[#304638] dark:bg-[#1d2d23] dark:text-white" /></div></div>{posts === null ? <Loading /> : <div className="grid gap-6 md:grid-cols-3">{posts.map((post, index) => <PostCard key={post.id} post={post} index={index} />)}</div>}</div></section>
    <section id="contact" className="bg-[#101a14] py-24 text-center text-white"><Sparkles className="mx-auto mb-5 text-blue-400" /><h2 className="serif text-5xl">Let’s build something useful.</h2><p className="mx-auto mt-5 max-w-lg text-gray-400">Have an opportunity or a question? My inbox is always open.</p><a href="mailto:akashbondada.dev@gmail.com" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-blue-500 px-5 py-3 text-sm font-semibold"><Mail size={16} /> Say hello</a></section>
  </main>;
}
