import { useEffect, useState } from 'react';
import { ArrowUpRight, Bot, Code2, Database, Download, Mail, Menu, Phone, Send, Server, ShieldCheck, Terminal, UserRound, X } from 'lucide-react';

const profile = {
  name: 'Bondada Akash', location: 'Hyderabad, India', phone: '+91 7075816998', email: 'akashbondada4@gmail.com',
  linkedin: 'https://www.linkedin.com/in/bondadaakash/?isSelfProfile=true', github: 'https://github.com/akashbondada1234'
};

const skills = [
  { icon: Code2, title: 'Development', items: ['Java', 'Python', 'JavaScript', 'Core Java', 'OOP', 'Data Structures'] },
  { icon: Server, title: 'Backend & APIs', items: ['Spring Boot', 'Spring MVC', 'Hibernate', 'JPA', 'JDBC', 'REST APIs', 'JSON', 'Postman'] },
  { icon: Database, title: 'Data', items: ['MySQL', 'Oracle 19C', 'SQL Server', 'RDBMS Design', 'Normalization', 'Joins', 'Indexing', 'Transactions'] },
  { icon: Terminal, title: 'Systems & Tools', items: ['Linux / Unix', 'Bash', 'Git', 'GitHub', 'Maven', 'Jenkins', 'Eclipse', 'VS Code', 'MySQL Workbench'] },
  { icon: ShieldCheck, title: 'API & Support Exposure', items: ['Apigee Edge/X', 'OAuth 2.0', 'JWT', 'API Keys', 'Quota', 'Spike Arrest', 'Splunk', 'AppDynamics', 'Autosys', 'ITIL'] },
  { icon: Code2, title: 'Frontend', items: ['HTML5', 'CSS3', 'JavaScript ES6 basics', 'Thymeleaf', 'Bootstrap'] }
];

const projects = [
  { group: 'Java Full Stack', title: 'Student Management System', tech: ['Java', 'Spring Boot', 'Spring MVC', 'MySQL', 'Thymeleaf', 'JPA', 'Hibernate'], text: 'A full-stack application for managing student records, course enrolments and academic results. Built CRUD flows, server-rendered pages, validation and REST endpoints with transactional data handling.' },
  { group: 'Python & Computer Vision', title: 'Hand Gesture Recognition with Voice Commands', tech: ['Python', 'TensorFlow', 'OpenCV', 'MediaPipe', 'SpeechRecognition'], text: 'A touchless human-computer interaction project combining gesture classification, hand landmark processing and speech recognition for hands-free device control. The resume records 95% gesture classification accuracy.' },
  { group: 'Database Design', title: 'Instagram Clone - Relational Database', tech: ['MySQL', 'SQL', 'MySQL Workbench'], text: 'Designed a normalized relational schema for users, posts, likes, comments, followers and hashtags, with foreign keys, indexes and analytical queries for feeds and engagement data.' },
  { group: 'Production Support Exposure', title: 'Application Log Monitor', tech: ['Bash', 'Unix/Linux', 'Shell Scripting'], text: 'A simulated L1 monitoring workflow that scans logs for errors, checks disk space and process health, rotates logs, and validates alert conditions for troubleshooting practice.' },
  { group: 'API & Apigee', title: 'Weather Data Integration API', tech: ['Apigee X', 'OpenWeatherMap', 'Swagger', 'Postman', 'Jenkins'], text: 'Exposed a third-party weather integration through an Apigee proxy with security, quota, caching, validation and repeatable CI/CD deployment practice.' },
  { group: 'API & Apigee', title: 'Online Bookstore API Gateway', tech: ['Apigee X', 'OAuth 2.0', 'Swagger', 'Postman', 'Jenkins'], text: 'A governed gateway concept routing Books, Users and Orders services through shared policy layers, consumer access controls and fault handling.' },
  { group: 'API & Apigee', title: 'Movie Info API Management System', tech: ['Apigee X', 'OMDb API', 'OAuth 2.0', 'Swagger', 'Postman'], text: 'Integrated the OMDb API through an Apigee gateway, centralizing authentication, response transformation and structured error handling.' }
];

function downloadResume() {
  const resumeWindow = window.open('', '_blank');
  if (!resumeWindow) return;
  const projectMarkup = projects.map(p => `<article><h3>${p.title}</h3><strong>${p.tech.join('  -  ')}</strong><p>${p.text}</p></article>`).join('');
  resumeWindow.document.write(`<!doctype html><html><head><title>Bondada Akash - Resume</title><style>
  *{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#17221f;max-width:900px;margin:20px auto;padding:38px 48px;background:#fff;box-shadow:0 12px 35px #17221f20;line-height:1.5}h1{font-size:30px;margin:0 0 4px}h2{font-size:13px;color:#c86b42;letter-spacing:1.4px;border-bottom:2px solid #1e302a;padding-bottom:7px;margin:26px 0 10px}h3{font-size:15px;margin:10px 0 2px}p{font-size:11px;margin:4px 0;color:#46554d}header p{font-size:11px;color:#56665e}article strong{font-size:10px;color:#b85e39;font-weight:normal}ul{font-size:11px;margin:5px 0;padding-left:18px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.contact{font-size:11px;color:#53635a}.skills{display:flex;flex-wrap:wrap;gap:6px}.skills span{background:#f3f7f2;border:1px solid #dce6dd;border-radius:4px;padding:6px 8px;font-size:10px;color:#405149}.social{display:flex;gap:10px;margin-top:8px}.social a{color:#b85e39;text-decoration:none;font-weight:bold;margin-right:8px}.social i{display:inline-grid;place-items:center;border:1px solid #b85e39;border-radius:3px;width:18px;height:18px;font-size:9px;font-style:normal;margin-right:4px}@media print{body{padding:20px 25px}h2{break-after:avoid}article{break-inside:avoid}}
  </style></head><body><header><h1>${profile.name}</h1><p><b>Full Stack Developer Candidate</b>  -  Java & Python  -  Spring Boot  -  REST APIs  -  SQL  -  Apigee</p><p class="contact">${profile.email} · ${profile.phone} · ${profile.location}</p><div class="social"><a href="${profile.linkedin}" target="_blank"><i>in</i> LinkedIn</a><a href="${profile.github}" target="_blank"><i>GH</i> GitHub</a></div></header><h2>PROFESSIONAL SUMMARY</h2><p>MCA graduate with Java Full Stack training and hands-on projects using Java, Spring Boot, Spring MVC, Hibernate, MySQL, Thymeleaf and REST APIs. Additional practical exposure to Apigee/API Management, Linux/Unix, SQL, monitoring and troubleshooting. Currently pursuing Python Full Stack training at Innomatics Research Labs, Hyderabad, since July 2026.</p><h2>TRAINING & PRACTICAL EXPOSURE</h2><div class="grid"><div><h3>Full Stack Developer Trainee</h3><p>Codegnan Destination, Hyderabad  -  Nov 2024 - May 2025</p><p>Java Full Stack training with Spring Boot, MVC, Hibernate, MySQL, Thymeleaf, REST APIs, Git and Agile/Scrum project practices.</p></div><div><h3>Apigee / API Management Training</h3><p>Bangalore · March 2026 - June 2026</p><p>Mentored practical training in Apigee Edge/X, REST APIs, OAuth 2.0, JWT, API keys, quota, spike arrest, API testing and API lifecycle concepts.</p></div><div><h3>Production / Application Support Training</h3><p>Bangalore · November 2025 - February 2026</p><p>Mentored practical training in Unix/Linux, SQL troubleshooting, monitoring with Splunk and AppDynamics, Autosys exposure and ITIL processes.</p></div><div><h3>Python Full Stack Training - Ongoing</h3><p>Innomatics Research Labs · Hyderabad · July 2026 - Ongoing</p><p>Currently continuing Full Stack development training with Python.</p></div></div><h2>CORE SKILLS</h2><div class="skills"><span>Java</span><span>Python</span><span>Spring Boot</span><span>Spring MVC</span><span>REST APIs</span><span>MySQL</span><span>SQL</span><span>Hibernate / JPA</span><span>HTML / CSS / JavaScript</span><span>Git / GitHub</span><span>Linux / Unix</span><span>Apigee</span><span>Postman</span><span>Splunk</span><span>AppDynamics</span><span>ITIL</span></div><h2>PROJECTS</h2>${projectMarkup}<h2>EDUCATION</h2><div class="grid"><div><h3>MCA (Computer Applications)</h3><p>Dr. Lankapalli Bullayya PG College, Andhra University, Visakhapatnam  -  2022-2024</p><p><b>CGPA: 7.02 / 10</b></p></div><div><h3>B.Sc (Computer Science)</h3><p>Andhra University, Visakhapatnam  -  2019-2022</p><p><b>CGPA: 6.16 / 10</b></p></div></div><h2>CERTIFICATIONS</h2><p>Java Developer Course - Codegnan Destination  -  The Joy of Computing using Python - NPTEL / IIT Madras</p><script>window.onload=()=>window.print()<\/script></body></html>`);
  resumeWindow.document.close();
}

function getAssistantReply(question) {
  const q = question.toLowerCase();
  if (q.includes('contact') || q.includes('email') || q.includes('phone')) return `You can contact Akash at ${profile.email} or ${profile.phone}. He is based in ${profile.location}.`;
  if (q.includes('github')) return `Akash's GitHub profile is available at ${profile.github}.`;
  if (q.includes('linkedin')) return `Akash's LinkedIn profile is available at ${profile.linkedin}.`;
  if (q.includes('education') || q.includes('degree') || q.includes('mca') || q.includes('bsc')) return 'Akash completed his B.Sc. in Computer Science at Aditya Degree College, Andhra University, Visakhapatnam (2019–2022, CGPA 6.16/10), followed by an MCA at Dr. Lankapalli Bullayya PG College, Andhra University, Visakhapatnam (2022–2024, CGPA 7.02/10).';
  if (q.includes('production') || q.includes('support') || q.includes('linux')) return 'Akash completed mentored Production/Application Support training in Bangalore from November 2025 to February 2026, covering Unix/Linux, SQL troubleshooting, monitoring, Splunk, AppDynamics, Autosys and ITIL.';
  if (q.includes('apigee') || q.includes('api management') || q.includes('api')) return 'Akash completed mentored Apigee/API Management training in Bangalore from March 2026 to June 2026, covering Apigee Edge/X, REST APIs, OAuth 2.0, JWT, API keys, quota, Spike Arrest, testing and lifecycle concepts.';
  if (q.includes('python')) return 'Akash is currently pursuing Python Full Stack training at Innomatics Research Labs in Hyderabad, started in July 2026.';
  if (q.includes('java') || q.includes('spring') || q.includes('skill')) return 'Akash’s core development direction includes Java, Spring Boot, Spring MVC, Hibernate/JPA, REST APIs, MySQL, SQL, HTML, CSS, JavaScript and Python.';
  if (q.includes('project')) return 'Featured projects include Student Management System, Hand Gesture Recognition with Voice Commands, Instagram Clone Database, Application Log Monitor, Weather Data Integration API, Online Bookstore API Gateway and Movie Info API Management System.';
  return 'I can answer questions about Akash’s skills, projects, education, training timeline, Apigee exposure, Production Support exposure and contact links.';
}

function App() {
  const [open, setOpen] = useState(false);
  const [projectFilter, setProjectFilter] = useState('All');
  const [selectedProject, setSelectedProject] = useState(null);
  const [assistantOpen, setAssistantOpen] = useState(false);
  const [question, setQuestion] = useState('');
  const [messages, setMessages] = useState([{ from: 'bot', text: 'Hi! Ask me about Akash’s skills, projects, education or training.' }]);
  useEffect(() => {
    const items = document.querySelectorAll('.section, .proof-strip');
    const observer = new IntersectionObserver(entries => entries.forEach(entry => {
      if (entry.isIntersecting) entry.target.classList.add('is-visible');
    }), { threshold: 0.12 });
    items.forEach(item => { item.classList.add('motion-ready'); observer.observe(item); });
    return () => observer.disconnect();
  }, []);
  const close = () => setOpen(false);
  const nav = id => { close(); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); };
  const askAssistant = event => { event.preventDefault(); const clean = question.trim(); if (!clean) return; setMessages(items => [...items, { from: 'user', text: clean }, { from: 'bot', text: getAssistantReply(clean) }]); setQuestion(''); };
  const quickAsk = prompt => setMessages(items => [...items, { from: 'user', text: prompt }, { from: 'bot', text: getAssistantReply(prompt) }]);
  return <div className="site">
    <header className="nav"><a className="logo" href="#home">BA<span>.</span></a><button className="menu" aria-label="Toggle navigation" onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button><nav className={open ? 'open' : ''}>{[['about','About'],['journey','Journey'],['skills','Skills'],['projects','Projects'],['experience','Experience'],['education','Education'],['contact','Contact']].map(([id,label]) => <a key={id} href={`#${id}`} onClick={close}>{label}</a>)}<button className="nav-download" onClick={downloadResume}><Download size={15}/> Resume PDF</button></nav></header>
    <main>
      <section id="home" className="hero section"><div className="hero-copy"><p className="kicker">MCA GRADUATE  -  FULL STACK DEVELOPER CANDIDATE</p><h1>Building practical software with a <em>full-stack mindset.</em></h1><p className="hero-text">I'm Akash, a Full Stack Developer candidate focused on Java, Spring Boot, Python, REST APIs and SQL - with additional practical exposure to Apigee/API Management and application support.</p><div className="actions"><a className="button primary" href="#projects">View projects <ArrowUpRight size={17}/></a><button className="button outline" onClick={downloadResume}><Download size={17}/> Download resume PDF</button></div><div className="quick-links"><a href={profile.github} target="_blank" rel="noreferrer"><Code2 size={16}/> GitHub</a><a href={profile.linkedin} target="_blank" rel="noreferrer"><UserRound size={16}/> LinkedIn</a><a href={`mailto:${profile.email}`}><Mail size={16}/> Email</a></div></div><div className="hero-card"><div className="photo-wrap"><img src="/profile.jpg" alt="Professional portrait of Bondada Akash"/><span>FULL STACK DEVELOPER</span></div><div className="terminal-top"><span/><span/><span/><small>akash@portfolio:~</small></div><div className="terminal-body"><p><b>$</b> whoami</p><h2>Full Stack Developer</h2><p><b>$</b> focus --now</p><div className="terminal-tags"><span>Java</span><span>Spring Boot</span><span>Python</span><span>REST APIs</span><span>SQL</span></div><p className="cursor"><b>$</b> currently training in Python Full Stack at Innomatics Research Labs<span>_</span></p></div></div></section>
       <section className="proof-strip"><div><b>B.Sc + MCA</b><span>Computer Science → Applications · 2019–2024</span></div><div><b>Java + Python</b><span>Development direction</span></div><div><b>Production Support</b><span>Training exposure</span></div><div><b>Apigee</b><span>API management exposure</span></div><div><b>Hyderabad</b><span>Open to opportunities</span></div></section>
      <section id="about" className="section two-col"><div><p className="kicker">01 / ABOUT ME</p><h2>A developer journey built around <em>learning by doing.</em></h2></div><div className="body-copy"><p>I completed my MCA in 2024 and began with Java Full Stack training at Codegnan, where I worked on end-to-end applications, REST APIs, relational data and collaborative development practices.</p><p>From November 2025 to February 2026, I completed mentored Production/Application Support training in Bangalore. From March 2026 to June 2026, I continued with mentored Apigee/API Management training, building practical understanding of gateways, security policies, Linux, monitoring, SQL and troubleshooting. I'm currently continuing that growth through Python Full Stack training at Innomatics Research Labs, which began in July 2026.</p><p className="callout">My goal is a Full Stack Developer or Software Developer opportunity where I can contribute, keep learning and build reliable applications.</p></div></section>
      <section id="journey" className="section tinted"><div className="section-head"><div><p className="kicker">02 / MY JOURNEY</p><h2>One continuous technical path.</h2></div><p>Development is the primary direction. API and support exposure strengthen the backend perspective.</p></div><div className="timeline"><div><b>2019 - 2022</b><h3>B.Sc (Computer Science)</h3><p>Aditya Degree College - Andhra University, Visakhapatnam<br/>CGPA: 6.16 / 10</p></div><div><b>2022 - 2024</b><h3>MCA (Computer Applications)</h3><p>Dr. Lankapalli Bullayya PG College - Andhra University, Visakhapatnam<br/>CGPA: 7.02 / 10</p></div><div><b>Nov 2024 - May 2025</b><h3>Java Full Stack training</h3><p>Full Stack Developer Trainee at Codegnan Destination, Hyderabad</p></div><div><b>Nov 2025 - Feb 2026</b><h3>Production / Application Support</h3><p>Separate mentored training in Bangalore covering SQL, Linux, monitoring and troubleshooting.</p></div><div><b>Mar 2026 - Jun 2026</b><h3>Apigee / API Management</h3><p>Mentored training in Bangalore covering Apigee, REST APIs, API security, policies and API testing.</p></div><div><b>July 2026 - Ongoing</b><h3>Python Full Stack training</h3><p>Innomatics Research Labs · Hyderabad · Current training focused on continuing my development direction.</p></div></div></section>
      <section id="skills" className="section"><div className="section-head"><div><p className="kicker">03 / TECHNICAL SKILLS</p><h2>Tools I use to turn ideas into working systems.</h2></div><p>Grouped for clarity, without subjective skill percentages.</p></div><div className="skill-grid">{skills.map(({icon: Icon,title,items}) => <article className="skill-card" key={title}><Icon size={21}/><h3>{title}</h3><div className="chips">{items.map(x => <span key={x}>{x}</span>)}</div></article>)}</div></section>
       <section id="projects" className="section tinted"><div className="section-head"><div><p className="kicker">04 / SELECTED WORK</p><h2>Proof through hands-on projects.</h2></div><div className="project-controls"><p>A selection of practical development, API, database and support projects.</p><label htmlFor="project-filter">Filter projects<select id="project-filter" value={projectFilter} onChange={event => setProjectFilter(event.target.value)}><option>All</option>{[...new Set(projects.map(project => project.group))].map(group => <option key={group}>{group}</option>)}</select></label></div></div><div className="project-grid">{projects.filter(project => projectFilter === 'All' || project.group === projectFilter).map((p,i) => <article className={`project-card ${i===0?'featured':''}`} key={p.title} role="button" tabIndex="0" onClick={() => setSelectedProject(p)} onKeyDown={event => (event.key === 'Enter' || event.key === ' ') && setSelectedProject(p)}><div className="project-visual" aria-label={`Conceptual technology flow: ${p.tech.join(' to ')}`}><span>{p.tech[0]}</span><i>→</i><span>{p.tech[Math.min(1,p.tech.length - 1)]}</span><i>→</i><span>{p.tech[p.tech.length - 1]}</span></div><div className="project-number">{String(i+1).padStart(2,'0')}</div><p className="project-group">{p.group}</p><h3>{p.title}</h3><p>{p.text}</p><div className="tech-list">{p.tech.map(t => <span key={t}>{t}</span>)}</div><span className="project-more">View details <ArrowUpRight size={14}/></span></article>)}</div></section>
      <section id="experience" className="section two-col"><div><p className="kicker">05 / TRAINING & EXPOSURE</p><h2>Experience, clearly and <em>honestly labeled.</em></h2></div><div className="experience-list"><article><span className="date">NOV 2024 - MAY 2025</span><h3>Full Stack Developer Trainee</h3><p className="company">Codegnan Destination  -  Hyderabad</p><p>Hands-on Java Full Stack training with Spring Boot, MVC, Hibernate, MySQL, Thymeleaf, REST APIs, validation, Git and Agile/Scrum project practices.</p></article><article><span className="date">NOV 2025 - FEB 2026 · BANGALORE</span><h3>Mentored Production / Application Support Training</h3><p>Unix/Linux, SQL troubleshooting, log analysis, monitoring concepts with Splunk and AppDynamics, Autosys exposure and ITIL processes.</p></article><article><span className="date">MAR 2026 - JUNE 2026 · BANGALORE</span><h3>Mentored API & Apigee Training</h3><p>Apigee Edge/X, API proxies, OAuth 2.0, JWT, API keys, quota, spike arrest, API testing, Swagger and API lifecycle concepts.</p></article><article><span className="date">JULY 2026 - ONGOING</span><h3>Python Full Stack</h3><p>Innomatics Research Labs · Hyderabad · Currently pursuing Python Full Stack training and expanding my software development toolkit.</p></article></div></section>
      <section id="education" className="section education"><p className="kicker">06 / EDUCATION & CERTIFICATIONS</p><h2>Strong academic foundation.</h2><div className="education-grid"><article><span>2022 - 2024</span><h3>MCA (Computer Applications)</h3><p>Dr. Lankapalli Bullayya PG College<br/>Andhra University  -  Visakhapatnam</p><b>CGPA 7.02 / 10</b></article><article><span>2019 - 2022</span><h3>B.Sc (Computer Science)</h3><p>Aditya Degree College<br/>Andhra University  -  Visakhapatnam</p><b>CGPA 6.16 / 10</b></article><article><span>2024</span><h3>Java Developer Course</h3><p>Codegnan Destination<br/>Core & Advanced Java</p><b>OOP  -  Collections  -  JDBC</b></article><article><span>JAN - APR 2023</span><h3>The Joy of Computing using Python</h3><p>NPTEL Online Certification<br/>IIT Madras</p><b>Elite certification</b></article></div></section>
      <section id="contact" className="contact section"><div><p className="kicker">07 / CONTACT</p><h2>Let's build the next chapter.</h2><p>I'm open to fresher and junior Full Stack Developer or Software Developer opportunities.</p></div><div className="contact-links"><a href={`mailto:${profile.email}`}><Mail/><span>Email<b>{profile.email}</b></span><ArrowUpRight/></a><a href={profile.linkedin} target="_blank" rel="noreferrer"><UserRound/><span>LinkedIn<b>Connect with me</b></span><ArrowUpRight/></a><a href={profile.github} target="_blank" rel="noreferrer"><Code2/><span>GitHub<b>View my repositories</b></span><ArrowUpRight/></a><a href={`tel:${profile.phone.replaceAll(' ','')}`}><Phone/><span>Phone<b>{profile.phone}</b></span><ArrowUpRight/></a></div></section>
    </main><footer><span>© 2026 Bondada Akash</span><span>Full Stack Developer candidate  -  Hyderabad</span></footer>{selectedProject && <div className="project-modal-backdrop" role="presentation" onClick={() => setSelectedProject(null)}><article className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-modal-title" onClick={event => event.stopPropagation()}><button className="modal-close" aria-label="Close project details" onClick={() => setSelectedProject(null)}><X size={18}/></button><p className="project-group">{selectedProject.group}</p><h2 id="project-modal-title">{selectedProject.title}</h2><p>{selectedProject.text}</p><h3>Technologies</h3><div className="tech-list">{selectedProject.tech.map(t => <span key={t}>{t}</span>)}</div><p className="modal-note">This project is presented as hands-on training and practical work.</p></article></div>}<button className="assistant-launch" aria-label="Open portfolio assistant" onClick={() => setAssistantOpen(!assistantOpen)}><Bot size={20}/><span>Ask about Akash</span></button>{assistantOpen && <aside className="assistant-panel" aria-label="Portfolio assistant"><div className="assistant-head"><div><span className="bot-orb"><Bot size={18}/></span><span><strong>Akash AI guide</strong><small>Verified portfolio assistant</small></span></div><button aria-label="Close assistant" onClick={() => setAssistantOpen(false)}><X size={17}/></button></div><div className="assistant-quick">{['What are his skills?','Show his projects','Explain his education','What is his Apigee exposure?','What is his career goal?'].map(prompt => <button key={prompt} onClick={() => quickAsk(prompt)}>{prompt}</button>)}</div><div className="assistant-messages">{messages.map((message, index) => <p className={message.from} key={`${message.from}-${index}`}>{message.text}</p>)}</div><form className="assistant-form" onSubmit={askAssistant}><input value={question} onChange={event => setQuestion(event.target.value)} placeholder="Ask about Akash..." aria-label="Ask about Akash"/><button aria-label="Send question"><Send size={16}/></button></form></aside>}
  </div>;
}
export default App;
